version: '3.9'
services:
  db:
    image: postgres:16
    container_name: gpt5_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-gpt5}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./apps/api
    container_name: gpt5_api
    environment:
      PORT: 4000
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/gpt5}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  web:
    build: ./apps/web
    container_name: gpt5_web
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: "http://api:4000"
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  db_data:
